module.exports = {
  "acoustic": "Acoustic",
  "original": "Original",
  "live": "Live",
  "coachella": "Coachella",
  "remix": "Remix",
  "mod club": "Mod Club",
  "lollapalooza": "Lollapalooza",
  "misc1": "Misc1",
  "misc live": "Misc Live",
  "singles & eps": "Singles & EPs",
  "single & eps": "Singles & EPs",
  "single & ep": "Singles & EPs",
  "singles & ep": "Singles & EPs",
  "released": "Released",
  "unreleased": "Unreleased",
  "shows": "Shows",
  "trilogy": "Trilogy",
  "instrumental": "Instrumental",
  "hidden": "Hidden",
  "deluxe": "Deluxe",
  "the idol": "The Idol",
  "alternate world": "Alternate World",
  "atlernate world": "Alternate World",
  "acapella": "Acapella",
  "a cappella": "Acapella",
  "compilation": "Compilation",
  "uncategorized": "Uncategorized",
  "radio edit": "Radio Edit",
  "bonus": "Bonus"
};